Repository Heptagram-Project/api, pull requests merged in 2022-10, with the labels that each got.

#139 Fix - Exception Handling
  package.json
  src/middleware/saveUserMetric.ts
Labels: hacktoberfest-accepted

#142 Added random number generator
  package.json
  src/app.ts
  src/routes/api.ts
  src/routes/api/randomnumber.ts
  yarn.lock
Labels: large, medium

#151 :wastebasket: Cleaning up the codebase
  src/app.ts
  src/functions/apiSpecs.ts
  src/functions/external/apis/GoogleSafeBrowsing.ts
  src/functions/external/apis/IpQualityScore.ts
  src/functions/external/apis/Phisherman.ts
  src/functions/external/apis/SinkingYahts.ts
  src/functions/external/apis/Walshy.ts
  src/functions/external/checkExternal.ts
  src/functions/external/reportExternal.ts
  src/functions/flattenLink.ts
  src/functions/fx.ts
  src/functions/getUserInfo.ts
  src/functions/validateEnv.ts
  src/index.ts
  src/middleware/hasLockedAccess.ts
  src/middleware/isAdmin.ts
  src/middleware/middleware.ts
  src/middleware/rateLimitController.ts
  src/middleware/saveUserMetric.ts
  src/routes/api/scam.ts
  src/routes/metrics/metrics.ts
  src/utils/checkExternal.ts
  src/utils/getHistory.ts
  src/utils/getLatitudeAndLongitude.ts
  src/utils/getLocationDetails.ts
  src/utils/getToken.ts
Labels: large

#156 Changelog endpoint
  package.json
  src/routes/api.ts
  src/routes/api/changelog.ts
Labels: large
